package io.temporal.scooterapp.ui;

import java.awt.Font;
import java.beans.PropertyChangeEvent;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class ScooterAppMainPanel extends javax.swing.JPanel {
    
    // NOTE: The limit reached and approval parts of the GUI are hidden
    // and not currently implemented 
    
    private static final Logger logger = LoggerFactory.getLogger(ScooterAppMainPanel.class);

    private AppController controller;
    
    public ScooterAppMainPanel(AppController controller) {
        this();
        
        this.controller = controller;
        controller.getModel().addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if (AppModel.PROP_NAME_SCOOTER_ID.equals(evt.getPropertyName())) {
                if (evt.getNewValue() == null) {
                    scooterPairStatusLabel.setText("<Not currently paired>");                    
                } else {
                    scooterPairStatusLabel.setText("Paired with scooter #" + evt.getNewValue());      
                    unlockScooterButton.setEnabled(true);
                    scooterPairStatusLabel.setEnabled(true);
                    scooterPairStatusLabel.setVisible(true);
                    pairWithScooterButton.setEnabled(false);
                }
            }
            if (AppModel.PROP_NAME_TOKENS_USED.equals(evt.getPropertyName())) {
                if (evt.getNewValue() == Integer.valueOf(0)) {
                    tokensConsumedLabel.setText("");
                    tokensConsumedLabel.setEnabled(false);
                } else {
                    tokensConsumedLabel.setText(evt.getNewValue() + " tokens consumed");
                    tokensConsumedLabel.setEnabled(false);
                }
            }
            if (AppModel.PROP_NAME_EMAIL_ADDRESS.equals(evt.getPropertyName())) {
                if (evt.getNewValue() == null) {
                    emailAddressButton.setText("Click to set email address");
                    unlockScooterButton.setEnabled(false);
                    scooterPairStatusLabel.setEnabled(false);
                    scooterPairStatusLabel.setVisible(false);
                    pairWithScooterButton.setEnabled(false);
                    tokensConsumedLabel.setEnabled(false);
                } else {
                    emailAddressButton.setText((String)evt.getNewValue());
                    scooterPairStatusLabel.setEnabled(true);
                    scooterPairStatusLabel.setVisible(true);
                    pairWithScooterButton.setEnabled(true);
                    tokensConsumedLabel.setEnabled(false);
                    unlockScooterButton.setEnabled(false);
                }
            }
        });
        
        // only show these when limit reached
        limitReachedLabel.setVisible(false);
        approveContinuationButton.setVisible(false);
    }
        
    /**
     * Creates new form ScooterAppMainPanel
     */
    public ScooterAppMainPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pairWithScooterButton = new javax.swing.JButton();
        scooterUnlockedStatusLabel = new javax.swing.JLabel();
        unlockScooterButton = new javax.swing.JButton();
        scooterPairStatusLabel = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        setSpeedLabel = new javax.swing.JLabel();
        slowerLabel = new javax.swing.JLabel();
        fasterLabel = new javax.swing.JLabel();
        rideStatusPanel = new javax.swing.JPanel();
        tokensConsumedLabel = new javax.swing.JLabel();
        endRideButton = new javax.swing.JButton();
        approveContinuationButton = new javax.swing.JButton();
        limitReachedLabel = new javax.swing.JLabel();
        emailAddressButton = new javax.swing.JButton();

        pairWithScooterButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pairWithScooterButton.setText("Pair with Scooter");
        pairWithScooterButton.setEnabled(false);
        pairWithScooterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pairWithScooterButtonActionPerformed(evt);
            }
        });

        scooterUnlockedStatusLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        unlockScooterButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        unlockScooterButton.setText("Unlock Scooter");
        unlockScooterButton.setEnabled(false);
        unlockScooterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockScooterButtonActionPerformed(evt);
            }
        });

        scooterPairStatusLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        scooterPairStatusLabel.setText("<Not currently paired>");
        scooterPairStatusLabel.setEnabled(false);

        speedSlider.setMaximum(50);
        speedSlider.setValue(20);
        speedSlider.setEnabled(false);

        setSpeedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        setSpeedLabel.setText("Speed");
        setSpeedLabel.setEnabled(false);

        slowerLabel.setText("Slower");
        slowerLabel.setEnabled(false);

        fasterLabel.setText("Faster");
        fasterLabel.setEnabled(false);

        tokensConsumedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tokensConsumedLabel.setEnabled(false);

        endRideButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        endRideButton.setText("End Ride");
        endRideButton.setEnabled(false);
        endRideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endRideButtonActionPerformed(evt);
            }
        });

        approveContinuationButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        approveContinuationButton.setText("Approve");
        approveContinuationButton.setEnabled(false);
        approveContinuationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveContinuationButtonActionPerformed(evt);
            }
        });

        limitReachedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        limitReachedLabel.setText("<html>Limit reached.<br>Click Approve within 5 seconds to continue ride.</html>");
        limitReachedLabel.setEnabled(false);

        javax.swing.GroupLayout rideStatusPanelLayout = new javax.swing.GroupLayout(rideStatusPanel);
        rideStatusPanel.setLayout(rideStatusPanelLayout);
        rideStatusPanelLayout.setHorizontalGroup(
            rideStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rideStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rideStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tokensConsumedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rideStatusPanelLayout.createSequentialGroup()
                        .addComponent(limitReachedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rideStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(approveContinuationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endRideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        rideStatusPanelLayout.setVerticalGroup(
            rideStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rideStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tokensConsumedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rideStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limitReachedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveContinuationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endRideButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        emailAddressButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailAddressButton.setText("Click to set email address");
        emailAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rideStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(setSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(unlockScooterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pairWithScooterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scooterPairStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scooterUnlockedStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailAddressButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slowerLabel)
                                .addGap(414, 414, 414)
                                .addComponent(fasterLabel))
                            .addComponent(speedSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(emailAddressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pairWithScooterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scooterPairStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scooterUnlockedStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unlockScooterButton))
                .addGap(61, 61, 61)
                .addComponent(setSpeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slowerLabel)
                    .addComponent(fasterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(rideStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pairWithScooterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pairWithScooterButtonActionPerformed

        class ScooterPairing extends SwingWorker<Void, Object> {
            @Override
            public Void doInBackground() {
                // simulate some work of identifying the scooter (e.g., via NFT or something)
                // This doesn't do anything with Temppral, it's just for show 
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    logger.error("Interrupted during sleep", ex);
                }
                return null;
            }

            @Override
            protected void done() {
                Random random = new Random();
                String scooterId = String.valueOf(random.nextInt(1000, 9999))   ;
                controller.getModel().setScooterId(scooterId);
            }
        }
        ScooterPairing pairing = new ScooterPairing();
        pairing.execute();
    }//GEN-LAST:event_pairWithScooterButtonActionPerformed

    private void endRideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRideButtonActionPerformed
        endRideButton.setEnabled(false);
        
        class RideEnder extends SwingWorker<Void, Void> {
            @Override
            public Void doInBackground() {
                controller.endWorkflow();
                return null;
            }

            @Override
            protected void done() {
                scooterUnlockedStatusLabel.setText("");
                scooterUnlockedStatusLabel.setEnabled(false);
                speedSlider.setEnabled(false);
                controller.getModel().setCurrentSpeed(0);
                pairWithScooterButton.setEnabled(true);
                unlockScooterButton.setEnabled(false);
                tokensConsumedLabel.setText("");
                tokensConsumedLabel.setEnabled(false);
                tokensConsumedLabel.setVisible(false);
                emailAddressButton.setEnabled(true);
                speedSlider.removeChangeListener(sliderListener);
            }
        }
        RideEnder ender = new RideEnder();
        ender.execute();
        
        
    }//GEN-LAST:event_endRideButtonActionPerformed

    private void approveContinuationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveContinuationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approveContinuationButtonActionPerformed

    private class SliderListener implements ChangeListener {

        @Override
        public void stateChanged(ChangeEvent e) {
            controller.getModel().setCurrentSpeed(speedSlider.getValue());
        }        
    }
    private final SliderListener sliderListener = new SliderListener();
    
    private void unlockScooterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockScooterButtonActionPerformed

        class RideStarter extends SwingWorker<Void, Void> {
            @Override
            public Void doInBackground() {
                controller.startWorkflow();
                return null;
            }

            @Override
            protected void done() {
                scooterUnlockedStatusLabel.setText("Scooter #" + controller.getModel().getScooterId() + " is unlocked");
                scooterUnlockedStatusLabel.setEnabled(true);
                scooterUnlockedStatusLabel.setVisible(true);
                
                speedSlider.setEnabled(true);
                slowerLabel.setEnabled(true);
                fasterLabel.setEnabled(true);
                setSpeedLabel.setEnabled(true);
                tokensConsumedLabel.setEnabled(true);
                tokensConsumedLabel.setVisible(true);
                emailAddressButton.setEnabled(false);
                
                controller.getModel().setCurrentSpeed(speedSlider.getValue());
                speedSlider.addChangeListener(sliderListener);
                
                unlockScooterButton.setEnabled(false);
                endRideButton.setEnabled(true);
            }
        }
        RideStarter starter = new RideStarter();
        starter.execute();
    }//GEN-LAST:event_unlockScooterButtonActionPerformed

    private void emailAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressButtonActionPerformed
        JLabel messageLabel = new JLabel("Specify Email Address");
        messageLabel.setFont(new Font("Helvetica Neue", Font.PLAIN, 18));
        String value = (String)JOptionPane.showInputDialog(this, messageLabel, "Identify Rider", JOptionPane.QUESTION_MESSAGE);
        if ("".equals(value)) {
            value = null;
        }
        controller.getModel().setEmailAddress(value);

    }//GEN-LAST:event_emailAddressButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveContinuationButton;
    private javax.swing.JButton emailAddressButton;
    private javax.swing.JButton endRideButton;
    private javax.swing.JLabel fasterLabel;
    private javax.swing.JLabel limitReachedLabel;
    private javax.swing.JButton pairWithScooterButton;
    private javax.swing.JPanel rideStatusPanel;
    private javax.swing.JLabel scooterPairStatusLabel;
    private javax.swing.JLabel scooterUnlockedStatusLabel;
    private javax.swing.JLabel setSpeedLabel;
    private javax.swing.JLabel slowerLabel;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JLabel tokensConsumedLabel;
    private javax.swing.JButton unlockScooterButton;
    // End of variables declaration//GEN-END:variables
}
